name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      has_site: ${{ steps.detect.outputs.has_site }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - id: detect
        name: Detect docs site
        run: |
          if [ -f docs/package.json ]; then
            echo "has_site=true" >> $GITHUB_OUTPUT
          else
            echo "has_site=false" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        if: steps.detect.outputs.has_site == 'true'
        run: cd docs && npm ci

      - name: 1. Check current directory and file existence
        run: |
          pwd
          ls -R ./docs

      - name: 2. Show <br> tags BEFORE replacement
        run: |
          echo "--- Searching for <br> in all .md files before replacement ---"
          grep -r --color=auto "<br>" ./docs || true

      - name: 3. Replace <br> with <br />
        run: |
          find ./docs -type f -name "*.md" -exec sed -i 's#<br>#<br />#g' {} +
          echo "Replacement command executed."

      - name: 4. Show <br> tags AFTER replacement
        run: |
          echo "--- Searching for <br> in all .md files after replacement ---"
          grep -r --color=auto "<br>" ./docs || true

      - name: Test build website
        if: steps.detect.outputs.has_site == 'true'
        run: cd docs && npm run build

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && needs.test.outputs.has_site == 'true'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: cd docs && npm ci

      - name: 1. Check current directory and file existence
        run: |
          pwd
          ls -R ./docs

      - name: 2. Show <br> tags BEFORE replacement
        run: |
          echo "--- Searching for <br> in all .md files before replacement ---"
          grep -r --color=auto "<br>" ./docs || true

      - name: 3. Replace <br> with <br />
        run: |
          find ./docs -type f -name "*.md" -exec sed -i 's#<br>#<br />#g' {} +
          echo "Replacement command executed."

      - name: 4. Show <br> tags AFTER replacement
        run: |
          echo "--- Searching for <br> in all .md files after replacement ---"
          grep -r --color=auto "<br>" ./docs || true

      - name: Build website
        run: cd docs && npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
